name: luca3m blog
url: "https://luca3m.me"
markdown: kramdown
exclude: [ "tailwind.config.js", "README.md", "CNAME" ]
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-tailwindcss

tailwind:
  config: "tailwind.config.js"
